application:
  subdomain: onedev
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  upstreams:
    - location: /
      backend: http://onedev-server:6610/
  ingress:
    - protocol: tcp
      port: 6611
      service: onedev-server
services:
  onedev-server:
    # 1dev/server:11.6.16
    # upstream: 1dev/server:16.2.0
    image: registry.lazycat.cloud/czyt/1dev/server:52d22f4002a19f3e
    binds:
      - /lzcapp/var/docker.sock:/var/run/docker.sock
      - /lzcapp/var/onedev:/opt/onedev
    environment:
      - initial_server_url=https://${LAZYCAT_APP_DOMAIN}
