package: cloud.lazycat.app.onedev
version: 11.6.16
name: OneDev
description: 一个开源的一体化 DevOps 平台
min_os_version: 1.5.0
homepage: https://onedev.io
author: onedev

permissions:
  required:
    - net.internet

locales:
  zh:
    name: OneDev
    description: 一个开源的一体化 DevOps 平台
  en:
    name: OneDev
    description: An open-source all-in-one DevOps platform
